# Generated by Django 2.0.1 on 2018-01-18 08:52

from django.db import migrations

def add_my_kitties(apps, schema):
    kitty_model = apps.get_model('registry', 'Kitty')
    my_kitty_ids = range(468312, 468629)
    for kitty_id in my_kitty_ids:
        kitty_model.objects.update_or_create(kitty_id=kitty_id)

class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_my_kitties)
    ]
