# Generated by Django 2.0.1 on 2018-01-18 09:07

from django.db import migrations, models
import django.db.models.deletion

def add_sizes(apps, schema):
    sizes_model = apps.get_model('registry', 'KittySize')
    sizes_model.objects.update_or_create(name='large', pixel_size='500')
    sizes_model.objects.update_or_create(name='medium', pixel_size='300')
    sizes_model.objects.update_or_create(name='small', pixel_size='100')

class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_add_my_kitties'),
    ]

    operations = [
        migrations.RunPython(add_sizes),
        migrations.AddField(
            model_name='kitty',
            name='kitty_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registry.KittySize'),
        ),
    ]
